---
- name: Assign roles to manager hosts
  hosts: manager
  become: true
  roles:
    - scs-mgr-dhcpd
    - osism.services.squid
    - osism.commons.motd
    - scs-landscape-nodes
    - scs-mgr-samba
    - scs-mgr-httpd
    - scs-mgr-tinyproxy
    - scs-dnscrypt
    - wireguard

- name: Assign roles to bastion hosts
  hosts: manager-infra
  become: true
  roles:
    - osism.commons.motd
    - scs-landscape-nodes
    - scs-mgr-dhcpd
    - scs-landscape-nodes
    - scs-mgr-tinyproxy
    - scs-dnscrypt
    - wireguard

