---
- name: Check the state of all ntp daemons
  hosts: generic
  gather_facts: no
  become: yes
  tasks:
    - name: Set time by http request to www.google.com
      shell: |
        /home/dragon/scripts/check_chrony.sh 3 0.01
      args:
        executable: /bin/bash

