---
- name: Assign roles to manager hosts
  hosts: manager
  become: true
  roles:
    - scs-mgr-dhcpd

- name: Assign roles to infrastructure hosts
  hosts: manager_infra
  become: true
  roles:
    - osism.services.wireguard
    - scs-landscape-nodes
    - osism.commons.motd
    - osism.services.squid
    - osism.services.chrony
    - scs-dnscrypt
    - scs-mgr-httpd
    - scs-mgr-samba
    - scs-mgr-tinyproxy

- name: Configure network rules on system boot
  hosts: manager_infra
  become: true
  tasks:
    - ansible.builtin.copy:
        dest: /etc/rc.local
        mode: 0755
        owner: root
        group: root
        content: |
          echo "Add nftables rules on system boot" | logger -s -t scs_add_nftables_rules
          /usr/local/scripts/scs_add_nftables_rules.sh

