---
- name: Synchronize date/time across remote hosts for an inital installation
  hosts: generic
  gather_facts: no
  become: yes
  tasks:
    - name: Set time by http request to www.google.com
      shell: |
        #!/bin/bash
        HOST=www.google.com
        DATESTRING=$(curl -k -sI "https://$HOST/" | grep -i "^date: ")

        if [[ $? -ne 0 ]]; then
                echo "Can't connect to $HOST"
                exit 1
        fi

        DATESTRING="$(echo "$DATESTRING"|sed '~s,date: ,,i;~s,^ *,,;~s, *$,,')"
        echo "Set system time"
        date -s "${DATESTRING}" > /dev/null
        echo "Set hardware clock"
        hwclock --systohc
        systemctl stop chrony.service
        sleep 2
        systemctl start chrony.service

        if [[ $? -ne 0 ]];then
           echo "Time setting failed - maybe you are not root?"
        fi
        date
      args:
        executable: /bin/bash

