---
- name: Assign roles to manager hosts
  hosts: manager
  become: true
  roles:
    - osism.services.squid
    - osism.commons.motd
    - scs-landscape-nodes
    - scs-mgr-samba
    - scs-mgr-httpd

