---
- name: Assign roles to manager hosts
  hosts: manager
  become: true
  roles:
    - scs-mgr-dhcpd

- name: Assign roles to infrastructure hosts
  hosts: manager_infra
  become: true
  roles:
    - osism.services.wireguard
    - scs-landscape-nodes
    - osism.commons.motd
    - osism.services.squid
    - osism.services.chrony
    - scs-dnscrypt
    - scs-mgr-httpd
    - scs-mgr-samba
    - scs-mgr-tinyproxy
