---
##########################################################
# ansible

ansible_host: 10.10.21.24

##########################################################
# generic

device_model: H12SSL-CT
internal_interface: dummy0
network_interface: dummy0
internal_address: 10.10.21.24

netdata_host_type: client

mgmt_address: 10.10.23.24
mgmt_mac: 3c:ec:ef:9b:12:cb


##########################################################
# network

network_type: netplan
network_ethernets:
  dummy0:
      addresses:
      - 10.10.21.24/32
      - fd0c:cc24:75a0:1:10:10:21:24/128

  enp66s0f0np0:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

  enp66s0f1np1:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

