---
- name: Check if Kind is installed
  stat:
    path: /usr/local/bin/kind
  register: check_file_status_kind

- name: Install kind
  shell: |
     curl -Lo /usr/local/bin/kind https://kind.sigs.k8s.io/dl/v0.25.0/kind-linux-amd64
     chmod 755 /usr/local/bin/kind
     chown root:root /usr/local/bin/kind
  when: not check_file_status_kind.stat.exists

- name: Create kind cluster
  shell: |
    if ! ( /usr/local/bin/kind get clusters|grep -q -P '^kind$' );then
      /usr/local/bin/kind create cluster
    fi
