#!/bin/bash

rundir="$(dirname $(readlink -f $0))/misc/manage"
cd "$rundir" || exit 1

source include.sh

if [ "$1" = "deps" ];then
   exit 0
fi
cd "$rundir" || exit 1
source venv/bin/activate
exec python3 ./landscape_ctl.py "$@"
