---
##########################################################
# ansible

ansible_host: 10.10.21.23

##########################################################
# generic

device_model: H12SSL-CT
internal_interface: dummy0
network_interface: dummy0
internal_address: 10.10.21.23

netdata_host_type: client

mgmt_address: 10.10.23.23
mgmt_mac: 3c:ec:ef:9e:d0:9b

frr_type: leaf
frr_local_as: 4210021023
frr_type: leaf
frr_loopback_v4: 10.10.21.23
frr_loopback_v6: fd0c:cc24:75a0:1:10:10:21:23

frr_uplinks:
- interface: enp66s0f0np0
    remote_as: 65405
- interface: enp66s0f1np1
    remote_as: 65404



##########################################################
# network

network_type: netplan

network_dummy_interfaces:
  - dummy0

network_ethernets_generated:
  dummy0:
      addresses:
      - 10.10.21.23/32
      - fd0c:cc24:75a0:1:10:10:21:23/128

  enp66s0f0np0:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

  enp66s0f1np1:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"


# Merge extra configuration with the generated configuration
network_ethernets: "{{ network_ethernets_generated | combine(network_ethernets_extra|default({}), recursive=True, list_merge='append_rp') }}"
