---
##########################################################
# ansible

ansible_host: 10.10.21.13

##########################################################
# generic

device_model: A2SDV-8C-LN8F
internal_interface: dummy0
internal_ip: 10.10.21.13
mgmt_ip: 10.10.23.13
mgmt_mac: 3c:ec:ef:5b:b5:bf


##########################################################
# network

network_type: netplan
network_ethernets:
  dummy0:
      addresses:
      - 10.10.21.13/32
      - fd0c:cc24:75a0:1:10:10:21:13/128

  enp2s0f0np0:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

  enp2s0f1np1:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

