---
##########################################################
# ansible

ansible_host: 10.10.21.25

##########################################################
# generic

device_model: H12SSL-NT
internal_interface: dummy0
internal_ip: 10.10.21.25
mgmt_ip: 10.10.23.25
mgmt_mac: 3c:ec:ef:9f:e2:40


##########################################################
# network

network_type: netplan
network_ethernets:
  dummy0:
      addresses:
      - 10.10.21.25/32
      - fd0c:cc24:75a0:1:10:10:21:25/128

  enp65s0f0np0:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

  enp65s0f1np1:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

