---
##########################################################
# ansible

ansible_host: 10.10.21.17

##########################################################
# generic

device_model: ARS-110M-NR
internal_interface: dummy0
internal_ip: 10.10.21.17
mgmt_ip: 10.10.23.17
mgmt_mac: 7c:c2:55:81:4a:86


##########################################################
# network

network_type: netplan
network_ethernets:
  dummy0:
      addresses:
      - 10.10.21.17/32
      - fd0c:cc24:75a0:1:10:10:21:17/128

  enp1p1s0f0np0:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

  enp1p1s0f1np1:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

