---
##########################################################
# ansible

ansible_host: 10.10.21.21

##########################################################
# generic

internal_interface: dummy0
internal_ip: 10.10.21.21
mgmt_ip: 10.10.23.21


##########################################################
# network

network_type: netplan
network_ethernets:
  dummy0:
      addresses:
      - 10.10.21.21/32
      - fd0c:cc24:75a0:1:10:10:21:21/128

  enp66s0f0np0:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

  enp66s0f1np1:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

