---
##########################################################
# ansible

ansible_host: 10.10.23.106

##########################################################
# generic

device_model: 7326-56X-O-AC-B
mgmt_mac: d0:77:ce:4b:b1:7a
serial_device: DIABb113318