---
##########################################################
# ansible

ansible_host: 10.10.21.26

##########################################################
# generic

device_model: H12SSL-NT
internal_interface: dummy0
network_interface: dummy0
internal_address: 10.10.21.26

netdata_host_type: client

mgmt_address: 10.10.23.26
mgmt_mac: 3c:ec:ef:9f:e2:4e

frr_type: leaf
frr_local_as: "4210021026"
frr_loopback_v4: 10.10.21.26
frr_loopback_v6: fd0c:cc24:75a0:1:10:10:21:26

frr_uplinks:
- interface: enp65s0f0np0
  remote_as: "65405"
- interface: enp65s0f1np1
  remote_as: "65404"



##########################################################
# network

network_type: netplan

network_dummy_interfaces:
  - dummy0

network_ethernets_generated:
  dummy0:
      addresses:
      - 10.10.21.26/32
      - fd0c:cc24:75a0:1:10:10:21:26/128

  enp65s0f0np0:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

  enp65s0f1np1:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"


# Merge extra configuration with the generated configuration
network_ethernets: "{{ network_ethernets_generated | combine(network_ethernets_extra|default({}), recursive=True, list_merge='append_rp') }}"
