---
# tasks file for scs-ceph-keys
- name: Create a file using the create_ceph_key_file - /tmp/secrets-ceph.yml
  create_ceph_key_file:
    target: "/tmp/secrets-ceph.yml"
    state: "present"
  tags:
    - create_secret
- name: Fetch file
  fetch:
    src: /tmp/secrets-ceph.yml
    dest: /tmp/secrets-ceph.yml
    flat: yes
  tags:
    - create_secret
- name: Encrypt the file
  local_action:
    module: command
    args:
      cmd: "ansible-vault encrypt /tmp/secrets-ceph.yml --output /tmp/secrets-ceph.yml.vaulted --vault-password-file /opt/configuration/secrets/vaultpass"
      creates: "/tmp/secrets-ceph.yml.vaulted"
  tags:
    - create_secret
- name: Copy file
  copy:
    src: "/tmp/secrets-ceph.yml.vaulted"
    dest: "/opt/configuration/environments/secrets-ceph.yml"
    mode: 0600
    decrypt: false
  tags:
    - create_secret

- name: Write content to files
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "/opt/configuration/{{ item.path }}.new"
    mode: '0600'
  loop: "{{ collected_ceph_keys }}"
  tags:
    - create_files

