---
- name: Create public network
  openstack.cloud.network:
    cloud: admin
    state: present
    name: public
    external: true
    provider_network_type: flat
    provider_physical_network: physnet1

- name: Create public subnet
  openstack.cloud.subnet:
    cloud: admin
    state: present
    name: subnet-public
    network_name: public
    cidr: 10.80.0.0/20
    enable_dhcp: false
    allocation_pool_start: 10.80.0.10
    allocation_pool_end: 10.80.15.254
    gateway_ip: 10.80.0.1
    dns_nameservers:
      - 10.10.21.10
      - 10.10.21.11
