mgmt_interface: eno6
external_interface: eno2
mgmt_address_system: 10.10.23.253

network_ethernets_extra:
  # Access to mangement network
  eno6:
    addresses:
      - "10.10.23.253/24"
  # Internet Uplink
  eno2:
    dhcp4: true
    dhcp6: false
#    addresses:
#      - "192.168.104.42/29"
#    nameservers:
#      addresses:
#      - 8.8.8.8
#      - 9.9.9.9
#      - 1.1.1.1
#    routes:
#    - to: default
#      via: 192.168.104.41
    mtu: 1500

network_tunnels:
  vxlan80:
    mode: vxlan
    id: 80
    local: 10.10.21.11
    addresses: [ 10.80.0.2/20 ]

