---
##########################
# netbox

netbox_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"
netbox_tag: 'v4.1.4'
netbox_userid: 'unit:root'
netbox_plugins_defaults:
  - netbox_initializers
netbox_plugins_extra:
  - netbox_config_diff
  - netbox_topology_views
netbox_plugins_config:
  netbox_config_diff:
    USERNAME: "admin"
    PASSWORD: "YourPaSsWoRd"
netbox_extra:
  SCRIPTS_ROOT: '/opt/netbox/netbox/scripts'
