---
- name: Install isc-dhcp-server package
  become: true
  ansible.builtin.dnf:
    name: "{{ isc_dhcp_server_package_name }}"
    state: present
    lock_timeout: "{{ lock_timeout | default(300) }}"

