# https://docs.debops.org/en/stable-3.1/ansible/roles/lvm/defaults/main.html#volume-groups-and-logical-volumes
- name: Manage LVM Logical Volumes
  community.general.lvol:
    lv: '{{ lv_item.lv }}'
    vg: '{{ lv_item.vg }}'
    size: '{{ lv_item.size }}'
    force: '{{ lv_item.force | d(omit) }}'
    state: 'present'
  loop: '{{ logical_volumes }}'
  loop_control:
    loop_var: lv_item
  tags: manage_lvm
- name: Mount LVM logical volmes
  ansible.builtin.mount:
    path: '{{ lv_item.mountpoint }}'
    src: '/dev/mapper/{{ lv_item.vg }}-{{ lv_item.lv }}'
    fstype: ext4
    opts: defaults,noatime,nodiratime
    state: mounted
  loop: '{{ logical_volumes }}'
  loop_control:
    loop_var: lv_item
  when: lv_item.mountpoint is defined
