- name: Activate rsyslog remote logging
  include_tasks: rsyslogd.yml
  when: rsyslogd_remote_logging == true

- name: Setup Node
  include_tasks: "{{ item }}"
  loop:
    - lvm.yml
    - sshd.yml
    - scripts.yml
    - vim.yml
    - packages.yml
    - workaround.yml
  tags: manage_lvm


