---
# https://www.brendangregg.com/blog/2024-03-24/linux-crisis-tools.html
- name: Install required packages
  become: true
  apt:
    update_cache: yes
    name:
      - procps
      - util-linux
      - sysstat
      - iproute2
      - numactl
      - tcpdump
      - linux-tools-common
      - "linux-generic-hwe-{{ ansible_distribution_version}}"
      - "linux-headers-generic-hwe-{{ ansible_distribution_version}}"
      - "linux-tools-generic-hwe-{{ ansible_distribution_version}}"
      - linux-tools-{{ ansible_kernel }}
      - bpfcc-tools
      - bpftrace
      - trace-cmd
      - nicstat
      - ethtool
      - tiptop
      - cpuid
      - msr-tools
      - iptraf-ng
      - tcpflow
      - iftop
      - pv
      - ncdu
      - nuttcp
      - pigz
    state: present
