---
- name: Copy rsyslog config
  ansible.builtin.template:
    src: 45-hardware.conf.j2
    dest: "/etc/rsyslog.d/45-hardware.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart rsyslog service
- ansible.builtin.copy:
    dest: /etc/cron.d/housekeeping-hardware-logs
    mode: 0755
    owner: root
    group: root
    content: |
       0 7 * * * /usr/bin/find /var/log/ -name "switches-????-??-??.log" -mtime +1 -exec gzip {} \;
       0 7 * * * /usr/bin/find /var/log/ -name "switches-????-??-??.log.gz" -mtime +14 -delete

       0 7 * * * /usr/bin/find /var/log/ -name "servers-????-??-??.log" -mtime +1 -exec gzip {} \;
       0 7 * * * /usr/bin/find /var/log/ -name "servers-????-??-??.log.gz" -mtime +14 -delete
