- name: Create ceph wrapper
  when: "'ceph-control' in group_names"
  tags: scripts
  copy:
    dest: /usr/local/bin/ceph
    mode: 0755
    owner: root
    group: users
    content: |
      #!/bin/bash

      CONTAINER_ID=$(docker ps --filter "name=ceph-mon-" --format \{\{.ID\}\} | head -n 1)

      if [ -z "$CONTAINER_ID" ]; then
        echo "No container found with a name starting with 'ceph-mon-'."
        exit 1
      fi

      docker exec -it "$CONTAINER_ID" /usr/bin/ceph --cluster ceph $@

- name: Synchronize all scs helper scripts
  become: false
  tags: scripts
  synchronize:
    src: "{{ role_path }}/files/scripts/"
    dest: /home/dragon/scripts
    owner: false
    delete: true
    dirs: true

