- name: Remove ceph wrapper
  become: yes
  file:
    path: /usr/local/bin/ceph
    state: absent

- name: Synchronize all scs helper scripts
  become: yes
  tags: scripts
  synchronize:
    src: "{{ role_path }}/files/scripts/"
    dest: /usr/local/scripts
    owner: false
    delete: true
    dirs: true

- name: Set permisssions for /usr/local/scripts and /opt/configuration
  become: yes
  shell: |
    /bin/bash /usr/local/scripts/scs_fix_permissions.sh
  args:
    executable: /bin/bash

- name: Create symbolic link to scs profile
  become: yes
  file:
    src: /usr/local/scripts/scs_profile.sh
    dest: /etc/profile.d/Z99-scs-env.sh
    state: link
