- name: Synchronize all scs helper scripts
  become: yes
  tags: scripts
  synchronize:
    src: "{{ role_path }}/files/scripts/"
    dest: /usr/local/scripts
    owner: false
    delete: true
    dirs: true

- name: Set permisssions for /usr/local/scripts and /opt/configuration
  become: yes
  ansible.builtin.command: "/bin/bash /usr/local/scripts/scs_fix_permissions.sh"

- name: Create symbolic link to scs profile
  become: yes
  file:
    src: /usr/local/scripts/scs_profile.sh
    dest: /etc/profile.d/Z99-scs-env.sh
    state: link

- name: Create symbolic link to scs profile
  become: yes
  file:
    src: /usr/local/scripts/scs_profile.sh
    dest: /etc/skel/.bash_profile
    state: link
