---
##########################################################
# ansible

ansible_host: 10.10.21.14

##########################################################
# generic

device_model: A2SDV-8C-LN8F
internal_interface: dummy0
network_interface: dummy0
internal_address: 10.10.21.14

netdata_host_type: client

mgmt_address: 10.10.23.14
mgmt_mac: 3c:ec:ef:5b:b5:bb


##########################################################
# network

network_type: netplan
network_ethernets:
  dummy0:
      addresses:
      - 10.10.21.14/32
      - fd0c:cc24:75a0:1:10:10:21:14/128

  enp2s0f0np0:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

  enp2s0f1np1:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

