#!/usr/bin/env python3

import argparse
import sys

from lib.global_helpers import setup_logging, generate_strings
from lib.landscape import OpenstackLandscape

parser = argparse.ArgumentParser(
    prog='Manage Landscape')

parser.add_argument('--log_level', metavar='loglevel', type=str,
                    default="INFO", help='The loglevel')

parser.add_argument('--verbose', '-v', action='store_true')

exclusive_group = parser.add_mutually_exclusive_group(required=True)

exclusive_group.add_argument('--create_domains', '-c', type=str, nargs="+", default=None,
                             help='A list of domains to be created')

exclusive_group.add_argument('--delete_domains', '-d', type=str, nargs="+", default=None,
                             help='A list of domains to be deleted')

parser.add_argument('--create_projects', '-p', type=str, nargs="+", default=["test1"],
                             help='A list of projects to be created in the created domains')

parser.add_argument('--create_machines', '-m', type=str, nargs="+", default=["test1"],
                             help='A list of vms to be created in the created domains')
args = parser.parse_args()

setup_logging(args.log_level)

os = OpenstackLandscape()

if args.create_domains:
    for new_domain in args.create_domains:
        new_domain_created = os.create_domain(new_domain, "Autogenerated domain", args.create_projects, args.create_machines)

if args.delete_domains:
    for delete_domain in args.delete_domains:
        os.delete_domain(delete_domain)

sys.exit(0)
