---
# tasks file for httpd

- name: Create required directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0775
  loop:
    - "{{ httpd_configuration_directory }}"
    - "{{ httpd_media_directory }}"
    - "{{ httpd_docker_compose_directory }}"

- name: Copy httpd configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ httpd_configuration_directory }}/{{ item }}"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  loop:
    - httpd.conf
  notify: Restart httpd service

- name: Copy docker-compose.yml file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ httpd_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  notify: Restart httpd service

- name: Manage httpd service
  become: true
  ansible.builtin.service:
    name: "{{ httpd_service_name }}"
    state: started
    enabled: true
