---
##########################################################
# ansible

ansible_host: 10.10.21.16

##########################################################
# generic

device_model: ARS-110M-NR
internal_interface: dummy0
network_interface: dummy0
internal_address: 10.10.21.16

netdata_host_type: client

mgmt_address: 10.10.23.16
mgmt_mac: 7c:c2:55:86:38:80

metal_lb_bgp_my_asn: 4210021016

##########################################################
# network

network_type: netplan

network_dummy_interfaces:
  - dummy0

network_ethernets_generated:
  dummy0:
      addresses:
      - 10.10.21.16/32
      - fd0c:cc24:75a0:1:10:10:21:16/128

  enp1p1s0f0np0:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"

  enp1p1s0f1np1:
      mtu: 9100
      dhcp4: "no"
      dhcp6: "no"


# Merge extra configuration with the generated configuration
network_ethernets: "{{ network_ethernets_generated | combine(network_ethernets_extra|default({}), recursive=True) }}"
