---

resolvconf_nameserver:
  - 8.8.8.8
  - 9.9.9.9
  - 1.1.1.1

# NTP server options.
chrony_server_options: iburst

# Configure Chrony to synchronize the hardware clock
chrony_sync_rtc: true

# Chrony limits access to clients that are on certain subnets.  Adjust the
# following subnets here to limit client access to chrony servers.
chrony_allowed_subnets:
  - 10.10.21.0/24
  - 10.10.23.0/24

chrony_bindaddresses:
  - "0.0.0.0"

# If set to true, chronyd will never open the server port and will operate
# strictly in a client-only mode.
chrony_bind_local_interfaces_only: false


chrony_servers:
  - ptbtime1.ptb.de
  - ptbtime2.ptb.de
  - ptbtime3.ptb.de
  - time.google.com
  - time.cloudflare.com

tinyproxy_allowed_networks:
  - 10.10.21.0/24
  - 10.10.23.0/24
  - 172.16.0.0/12
  - 10.80.0.0/20

#tinyproxy_allowed_domains:
#  - ^.*debian.*$
#  - ^.*ubuntu.*$

logical_volumes:
  - lv: 'log'
    vg: 'system'
    size: '30G'
    resizefs: true
    force: true
  - lv: 'docker'
    vg: 'system'
    size: '150G'
    resizefs: true
    force: true
  - lv: 'home'
    vg: 'system'
    size: '50G'
    resizefs: true
    force: true


wireguard_server_address: 10.10.1.1/24
wireguard_listen_port: 51820
wireguard_client_allowed_ips: 10.10.1.0/24,10.10.23.0/24,10.10.24.0/24,10.10.21.0/24,10.10.22.0/24,10.80.0.0/20

# Debug: 
# echo module wireguard +p > /sys/kernel/debug/dynamic_debug/control
# journalctl -f

wireguard_users:
  - name: scoopex
    key: 3XfXCmSo5+2kCrUgI/OmQDxSrx3gnomvFESNUhXVflw=
    ip: 10.10.1.20
  - name: matofeder
    key: EkL7bli2t4EJSDYo4Edyhg8enHI1zOR+A54Ghco1OlY=
    ip: 10.10.1.21
  - name: gtema
    key: PoXN8ZMMQdJM+BQ/XI/uu/nODCiE9FzZ1mRIEIFbKXs=
    ip: 10.10.1.22
  - name: bitkeks
    key: i5zuiuEhpRQiXTEgeDjfWCPnKCxx9SpaxpLKjZsgok8=
    ip: 10.10.1.23
    state: absent
  - name: fkr
    key: 0CcpoKi2d+fYeeIQutKWZ4nHc4fKyULjQBwMzAidiT4=
    ip: 10.10.1.24
  - name: jschoone
    key: V83VIcgBKmEPqaugVnh0J3/dnpHhSxKkxRHvw89SABs=
    ip: 10.10.1.25
