---
# tasks file for samba

- name: Create required directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  loop:
    - "{{ samba_configuration_directory }}"
    - "{{ samba_configuration_directory }}/conf.d"
    - "{{ samba_docker_compose_directory }}"

- name: Copy samba configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ samba_configuration_directory }}/conf.d/{{ item }}"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  loop:
    - osism.conf
  notify: Restart samba service

- name: Remove osism_allow_list.conf configuration file
  ansible.builtin.file:
    path: "{{ samba_configuration_directory }}/conf.d/osism_allow_list.conf"
    state: absent

- name: Copy docker-compose.yml file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ samba_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  notify: Restart samba service

- name: Manage samba service
  become: true
  ansible.builtin.service:
    name: "{{ samba_service_name }}"
    state: started
    enabled: true
