---
galaxy_info:
  author: Marc Schoechlin
  description: Role osism.services.rng
  company: SBA e.V.
  license: Apache License 2.0
  min_ansible_version: 2.16.0
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - osism
    - system
dependencies: []
