---
##########################################################
# ansible

ansible_host: 192.168.16.5

##########################################################
# generic

internal_interface: eno1

##########################################################
# network

network_type: netplan
network_ethernets:
  eno1:
    addresses:
      - "192.168.16.10/20"
    gateway4: "192.168.16.1"
    mtu: 1500
