---
##########################################################
# ansible

#External
ansible_host: 188.244.101.28

#Internal
#ansible_host: 192.168.104.43

##########################################################
# generic

internal_interface: eno2

##########################################################
# network

network_type: netplan
network_ethernets:
  eno2:
    addresses:
      - "192.168.104.43/29"
    gateway4: "192.168.104.41"
    mtu: 1500
