---
##########################################################
# images

docker_registry: quay.io

# proxy
container_http_proxy: "http://{{ groups['manager'][0] }}:8888"
container_https_proxy: "http://{{ groups['manager'][0] }}:8888"
container_no_proxy: "localhost,127.0.0.1,api-internal.zone1.landscape.scs.community"

##########################################################
# loadbalancer

kolla_internal_fqdn: api-internal.zone1.landscape.scs.community
kolla_external_fqdn: api.zone1.landscape.scs.community

kolla_internal_vip_address: 10.10.21.200
kolla_external_vip_address: 10.10.21.201

kolla_enable_tls_external: "yes"
kolla_enable_tls_internal: "yes"

# Because we use a layer3 underlay, we disable keepalived
# https://docs.openstack.org/kolla-ansible/latest/reference/high-availability/haproxy-guide.html
#
# When already active
# osism console --type clush control
# >sudo systemctl disable kolla-keepalived-container.service
# >sudo systemctl stop kolla-keepalived-container.service
# >sudo systemctl status kolla-keepalived-container.service
enable_keepalived: no

##########################################################
# openstack

# disable services
enable_heat: "no"

# generic
openstack_service_workers: 5

# elasticsearch
es_heap_size: "4g"

# neutron
neutron_plugin_agent: "ovn"
neutron_ovn_availability_zones: [nova]

# octavia
octavia_network_type: tenant

# designate
designate_ns_record: openstack.zone1.landscape.scs.community

##########################################################
# ceph rgw integration

enable_ceph_rgw: true
enable_ceph_rgw_keystone: true

ceph_rgw_swift_compatibility: false
ceph_rgw_swift_account_in_url: true

##########################################################
# external ceph

cinder_backend_ceph: "yes"
glance_backend_ceph: "yes"
gnocchi_backend_storage: "ceph"
nova_backend_ceph: "yes"

ceph_gnocchi_pool_name: "metrics"
cinder_backup_driver: "ceph"
glance_backend_file: "no"

# NOTE: public_network from environments/ceph/configuration.yml
ceph_public_network: 10.10.21.0/22

##########################################################
# keystone
keystone_identity_providers:
  - name: "keycloak"
    openstack_domain: "keycloak"
    protocol: "openid"
    identifier: "https://keycloak.testbed.osism.xyz/auth/realms/osism"
    public_name: "Authenticate via Keycloak"
    attribute_mapping: "mappingId1"
    metadata_folder: "{{ node_custom_config }}/keystone/federation/oidc/metadata"
    certificate_file: "{{ node_custom_config }}/keystone/federation/oidc/kD9RIBcPiCOVO8wOM2VbZD5XnpgSkf-tWdSmhurxmJo.pem"
keystone_identity_mappings:
  - name: "mappingId1"
    file: "{{ node_custom_config }}/keystone/federation/oidc/attribute_maps/oidc_attribute_mappingId1.json"
# Keystone auth endpoint
keystone_logout_url: "https://api.testbed.osism.xyz/auth/"

#########################################################
# other

enable_proxysql: no
# BEGIN: TLS
kolla_copy_ca_into_containers: "yes"
openstack_cacert: /etc/ssl/certs/ca-certificates.crt
# END: TLS
