---
##########################################################
# ansible

ansible_host: 10.10.23.110

##########################################################
# generic

device_model: 7726-32X-O-AC-B
mgmt_mac: 90:2d:77:58:27:50
mgmt_address: 10.10.23.110
serial_device: BCBRb113318
bgp_asn: 65501

