

resolvconf_nameserver:
  - 8.8.8.8
  - 9.9.9.9
  - 1.1.1.1

# NTP server options.
chrony_server_options: iburst

# Configure Chrony to synchronize the hardware clock
chrony_sync_rtc: true

# Chrony limits access to clients that are on certain subnets.  Adjust the
# following subnets here to limit client access to chrony servers.
chrony_allowed_subnets:
  - 10.10.21.0/24
  - 10.10.23.0/24

# If set to true, chronyd will never open the server port and will operate
# strictly in a client-only mode.
chrony_bind_local_interfaces_only: false


chrony_servers:
  - ptbtime1.ptb.de
  - ptbtime2.ptb.de
  - ptbtime3.ptb.de
  - time.google.com
  - time.cloudflare.com

tinyproxy_allowed_networks:
  - 10.10.21.0/24
  - 10.10.23.0/24

#tinyproxy_allowed_domains:
#  - ^.*debian.*$
#  - ^.*ubuntu.*$


logical_volumes:
  - lv: 'log'
    vg: 'system'
    size: '30G'
    resizefs: true
    force: true
  - lv: 'docker'
    vg: 'system'
    size: '100G'
    resizefs: true
    force: true
